### ISSUE TITLE
ajax queries to "http://localhost:8080/epcis/Something" may result in CORS problems

### ISSUE THREAD

**Issue by dmelo** [JaewookByun/epcis#22]
I'm not sure if there is a reason for it. On the file `epcis/src/main/webapp/rest-like_query_service.html`, for instance, there are several entries of "http://localhost:8080/epcis/.*" that are used to define the address for the ajax call. If I access it, on my browser, using http://localhost:8080/epcis, everything works fine.

But, if I (or a coworker) access it from my IP "http://192.168.0.10:8080/epcis/.*" then the browser detects cross scripting, and blocks the request. One way to solve this is making the URL relative "/epcis/.*" instead. If there is no special reason to point to localhost, I can change it on my repo and make a PR.

**Comment by JaewookByun** [comment]
Dear, Diogo Oliveira de Melo

The web page, ./rest-like_query_service.html, is an educational client page, which makes someone understand how to use epcis query service as well as invoke services in any remote servers. 

If you install epcis and use this page, then the 'localhost' works. 
But, (for example), for the temporary server ( http://143.248.56.100:8080/epcis/rest-like_query_service.html ), you need to change the address. 

Thanks for your comment. 
Definitely, changing 'http://localhost:8080/epcis/Service/_' to './Service/_' makes it work. But, it limits it to local invocation which is not my intention.
