### ISSUE TITLE
404 error occurred...

### ISSUE THREAD

**Issue by cmdhema** [JaewookByun/epcis#30]
war 파일 복사후 tomcat을 실행했는데 localhost:8080/epcis 를 호출하면 404에러가 납니다. epcis 외 다른어플리케이션들은 실행이 되는 상황입니다. 혹시 수정해야할 파일이 있나요?
Tomcat 버전은 8.5.5 버전입니다.

Translated Question:
I faced 404 error after running Tomcat 8.5.5 with epcis.war file even though other applications (maybe, other web application on top of Tomcat) run successfully.

Is there any more setting for running Oliot epcis?

**Comment by JaewookByun** [comment]
Hi, 
Please ask a question in English in the next question(s).

1) Did you run MongoDB v3.2 before running tomcat?
2) What is your other running environment such as operating system? 
I can guarantee that there hasn't been any problems in Linux operating system. 

Regards,
Jaewook Byun

**Comment by JaewookByun** [comment]
Could you edit your issue title in English?

**Comment by JaewookByun** [comment]
If any responses are given within one day, this issue will be manually closed.

**Comment by cmdhema** [comment]
I use Mac os sierra.. I will try linux. Thanks

**Comment by JaewookByun** [comment]
Thank you for your reply. 

I don't think the type of operating system results in the 404 error.
If you cannot run epcis on top of Mac, it would be the problem we should resolve. 
Have you checked the log file of Tomcat?

Thank you~

**Comment by yalewkidane** [comment]
i used mac (OS X EI Capitan ) and it works fine. The problem must be other. Make sure u have also used jdk instead of jre.

**Comment by cmdhema** [comment]
Thanks. I will check my environment.

**Comment by JaewookByun** [comment]
I'm wondering if you have resolved the issue. 
If you did so, could you share your experience for the community?

**Comment by JaewookByun** [comment]
Due to no response, I close this issue.

**Comment by cmdhema** [comment]
Sorry I try install now. I uninstall existing tomcat and reinstall using brew. Now I can access epcis on tomcat. Thanks.
