### ISSUE TITLE
could not start epcis on windows 10 with java 10, Tomcat 8, and MongoDB 3.2

### ISSUE THREAD

**Issue by thomaskarlrichter** [JaewookByun/epcis#37]
according to your Installation procedure 
1. Installation as User
Jaewook Byun edited this page on 6 Oct 2016 · 1 revision

I installed epcis.war
 but got the following error in the log:

17-Jul-2018 12:43:40.181 INFORMATION [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.5.32
17-Jul-2018 12:43:40.187 INFORMATION [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Jun 20 2018 19:50:35 UTC
17-Jul-2018 12:43:40.188 INFORMATION [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.5.32.0
17-Jul-2018 12:43:40.188 INFORMATION [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Windows 10
17-Jul-2018 12:43:40.188 INFORMATION [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            10.0
17-Jul-2018 12:43:40.188 INFORMATION [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
17-Jul-2018 12:43:40.189 INFORMATION [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             C:\Program Files\Java\jre-10.0.1
17-Jul-2018 12:43:40.189 INFORMATION [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           10.0.1+10
17-Jul-2018 12:43:40.189 INFORMATION [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            "Oracle Corporation"
17-Jul-2018 12:43:40.189 INFORMATION [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         C:\Program Files\Apache Software Foundation\Tomcat 8.5
17-Jul-2018 12:43:40.189 INFORMATION [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         C:\Program Files\Apache Software Foundation\Tomcat 8.5
17-Jul-2018 12:43:40.189 INFORMATION [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=C:\Program Files\Apache Software Foundation\Tomcat 8.5
17-Jul-2018 12:43:40.190 INFORMATION [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=C:\Program Files\Apache Software Foundation\Tomcat 8.5
17-Jul-2018 12:43:40.190 INFORMATION [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=C:\Program Files\Apache Software Foundation\Tomcat 8.5\temp
17-Jul-2018 12:43:40.190 INFORMATION [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
17-Jul-2018 12:43:40.190 INFORMATION [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=C:\Program Files\Apache Software Foundation\Tomcat 8.5\conf\logging.properties
17-Jul-2018 12:43:40.190 INFORMATION [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.lang=ALL-UNNAMED
17-Jul-2018 12:43:40.191 INFORMATION [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.io=ALL-UNNAMED
17-Jul-2018 12:43:40.191 INFORMATION [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
17-Jul-2018 12:43:40.191 INFORMATION [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: exit
17-Jul-2018 12:43:40.191 INFORMATION [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: abort
17-Jul-2018 12:43:40.191 INFORMATION [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xms128m
17-Jul-2018 12:43:40.192 INFORMATION [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xmx256m
17-Jul-2018 12:43:40.192 INFORMATION [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [C:\Program Files\Apache Software Foundation\Tomcat 8.5\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\Haskell\bin;C:\Program Files\Haskell Platform\8.4.2\lib\extralibs\bin;C:\Program Files\Haskell Platform\8.4.2\bin;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;c:\Program Files\Intel\WiFi\bin\;c:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Haskell Platform\8.4.2\mingw\bin;C:\Program Files\nodejs\;C:\Program Files\Microsoft VS Code\bin;C:\WINDOWS\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;.]
17-Jul-2018 12:43:40.251 INFORMATION [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8089"]
17-Jul-2018 12:43:40.314 INFORMATION [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
17-Jul-2018 12:43:40.323 INFORMATION [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"]
17-Jul-2018 12:43:40.325 SCHWERWIEGEND [main] org.apache.catalina.core.StandardService.initInternal Failed to initialize connector [Connector[AJP/1.3-8009]]
 org.apache.catalina.LifecycleException: Failed to initialize component [Connector[AJP/1.3-8009]]
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:112)
	at org.apache.catalina.core.StandardService.initInternal(StandardService.java:549)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107)
	at org.apache.catalina.core.StandardServer.initInternal(StandardServer.java:875)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107)
	at org.apache.catalina.startup.Catalina.load(Catalina.java:632)
	at org.apache.catalina.startup.Catalina.load(Catalina.java:655)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.catalina.startup.Bootstrap.load(Bootstrap.java:309)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:492)
Caused by: org.apache.catalina.LifecycleException: Protocol handler initialization failed
	at org.apache.catalina.connector.Connector.initInternal(Connector.java:995)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107)
	... 12 more
Caused by: java.net.BindException: Address already in use: bind
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Unknown Source)
	at java.base/sun.nio.ch.Net.bind(Unknown Source)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
	at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:210)
	at org.apache.tomcat.util.net.AbstractEndpoint.init(AbstractEndpoint.java:1086)
	at org.apache.tomcat.util.net.AbstractJsseEndpoint.init(AbstractJsseEndpoint.java:268)
	at org.apache.coyote.AbstractProtocol.init(AbstractProtocol.java:581)
	at org.apache.catalina.connector.Connector.initInternal(Connector.java:993)
	... 13 more

17-Jul-2018 12:43:40.327 INFORMATION [main] org.apache.catalina.startup.Catalina.load Initialization processed in 747 ms
17-Jul-2018 12:43:40.411 INFORMATION [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
17-Jul-2018 12:43:40.411 INFORMATION [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.32
17-Jul-2018 12:43:40.427 INFORMATION [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [C:\Program Files\Apache Software Foundation\Tomcat 8.5\webapps\docs]
17-Jul-2018 12:43:40.925 INFORMATION [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [C:\Program Files\Apache Software Foundation\Tomcat 8.5\webapps\docs] has finished in [498] ms
17-Jul-2018 12:43:40.926 INFORMATION [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [C:\Program Files\Apache Software Foundation\Tomcat 8.5\webapps\manager]
17-Jul-2018 12:43:40.990 INFORMATION [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [C:\Program Files\Apache Software Foundation\Tomcat 8.5\webapps\manager] has finished in [64] ms
17-Jul-2018 12:43:40.991 INFORMATION [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [C:\Program Files\Apache Software Foundation\Tomcat 8.5\webapps\ROOT]
17-Jul-2018 12:43:41.026 INFORMATION [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [C:\Program Files\Apache Software Foundation\Tomcat 8.5\webapps\ROOT] has finished in [35] ms
17-Jul-2018 12:43:41.032 INFORMATION [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8089"]
17-Jul-2018 12:43:41.049 INFORMATION [main] org.apache.catalina.startup.Catalina.start Server startup in 721 ms
17-Jul-2018 12:44:10.890 INFORMATION [http-nio-8089-exec-6] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [C:\Program Files\Apache Software Foundation\Tomcat 8.5\webapps\epcis.war]
17-Jul-2018 12:44:15.506 INFORMATION [http-nio-8089-exec-6] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
17-Jul-2018 12:44:16.354 INFORMATION [http-nio-8089-exec-6] com.mongodb.diagnostics.logging.JULLogger.log Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
17-Jul-2018 12:44:16.468 INFORMATION [cluster-ClusterId{value='5b4dc880b65c2c23546b8d0c', description='null'}-localhost:27017] com.mongodb.diagnostics.logging.JULLogger.log Opened connection [connectionId{localValue:1, serverValue:23}] to localhost:27017
17-Jul-2018 12:44:16.472 INFORMATION [cluster-ClusterId{value='5b4dc880b65c2c23546b8d0c', description='null'}-localhost:27017] com.mongodb.diagnostics.logging.JULLogger.log Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 2, 21]}, minWireVersion=0, maxWireVersion=4, maxDocumentSize=16777216, roundTripTimeNanos=835352}
17-Jul-2018 12:44:16.571 INFORMATION [http-nio-8089-exec-6] com.mongodb.diagnostics.logging.JULLogger.log Opened connection [connectionId{localValue:2, serverValue:24}] to localhost:27017
17-Jul-2018 12:44:16.606 SCHWERWIEGEND [http-nio-8089-exec-6] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
17-Jul-2018 12:44:16.607 SCHWERWIEGEND [http-nio-8089-exec-6] org.apache.catalina.core.StandardContext.startInternal Context [/epcis] startup failed due to previous errors
17-Jul-2018 12:44:16.660 WARNUNG [http-nio-8089-exec-6] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [epcis] appears to have started a thread named [cluster-ClusterId{value='5b4dc880b65c2c23546b8d0c', description='null'}-localhost:27017] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@10.0.1/jdk.internal.misc.Unsafe.park(Native Method)
 java.base@10.0.1/java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
 java.base@10.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source)
 com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.waitForSignalOrTimeout(DefaultServerMonitor.java:224)
 com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.waitForNext(DefaultServerMonitor.java:205)
 com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:153)
 java.base@10.0.1/java.lang.Thread.run(Unknown Source)
17-Jul-2018 12:44:16.661 WARNUNG [http-nio-8089-exec-6] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [epcis] appears to have started a thread named [pool-2-thread-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@10.0.1/jdk.internal.misc.Unsafe.park(Native Method)
 java.base@10.0.1/java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
 java.base@10.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source)
 java.base@10.0.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
 java.base@10.0.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
 java.base@10.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
 java.base@10.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
 java.base@10.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
 java.base@10.0.1/java.lang.Thread.run(Unknown Source)
17-Jul-2018 12:44:16.662 WARNUNG [http-nio-8089-exec-6] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [epcis] appears to have started a thread named [DefaultQuartzScheduler_Worker-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@10.0.1/java.lang.Object.wait(Native Method)
 org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:568)
17-Jul-2018 12:44:16.664 WARNUNG [http-nio-8089-exec-6] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [epcis] appears to have started a thread named [DefaultQuartzScheduler_Worker-2] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@10.0.1/java.lang.Object.wait(Native Method)
 org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:568)
17-Jul-2018 12:44:16.665 WARNUNG [http-nio-8089-exec-6] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [epcis] appears to have started a thread named [DefaultQuartzScheduler_Worker-3] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@10.0.1/java.lang.Object.wait(Native Method)
 org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:568)
17-Jul-2018 12:44:16.666 WARNUNG [http-nio-8089-exec-6] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [epcis] appears to have started a thread named [DefaultQuartzScheduler_Worker-4] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@10.0.1/java.lang.Object.wait(Native Method)
 org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:568)
17-Jul-2018 12:44:16.667 WARNUNG [http-nio-8089-exec-6] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [epcis] appears to have started a thread named [DefaultQuartzScheduler_Worker-5] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@10.0.1/java.lang.Object.wait(Native Method)
 org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:568)
17-Jul-2018 12:44:16.668 WARNUNG [http-nio-8089-exec-6] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [epcis] appears to have started a thread named [DefaultQuartzScheduler_Worker-6] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@10.0.1/java.lang.Object.wait(Native Method)
 org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:568)
17-Jul-2018 12:44:16.668 WARNUNG [http-nio-8089-exec-6] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [epcis] appears to have started a thread named [DefaultQuartzScheduler_Worker-7] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@10.0.1/java.lang.Object.wait(Native Method)
 org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:568)
17-Jul-2018 12:44:16.669 WARNUNG [http-nio-8089-exec-6] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [epcis] appears to have started a thread named [DefaultQuartzScheduler_Worker-8] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@10.0.1/java.lang.Object.wait(Native Method)
 org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:568)
17-Jul-2018 12:44:16.670 WARNUNG [http-nio-8089-exec-6] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [epcis] appears to have started a thread named [DefaultQuartzScheduler_Worker-9] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@10.0.1/java.lang.Object.wait(Native Method)
 org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:568)
17-Jul-2018 12:44:16.671 WARNUNG [http-nio-8089-exec-6] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [epcis] appears to have started a thread named [DefaultQuartzScheduler_Worker-10] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@10.0.1/java.lang.Object.wait(Native Method)
 org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:568)
17-Jul-2018 12:44:16.672 WARNUNG [http-nio-8089-exec-6] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [epcis] appears to have started a thread named [DefaultQuartzScheduler_QuartzSchedulerThread] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@10.0.1/java.lang.Object.wait(Native Method)
 org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:427)
17-Jul-2018 12:44:16.692 INFORMATION [http-nio-8089-exec-6] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [C:\Program Files\Apache Software Foundation\Tomcat 8.5\webapps\epcis.war] has finished in [5,802] ms
17-Jul-2018 12:44:25.207 INFORMATION [http-nio-8089-exec-3] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
17-Jul-2018 12:44:25.738 INFORMATION [http-nio-8089-exec-3] com.mongodb.diagnostics.logging.JULLogger.log Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
17-Jul-2018 12:44:25.825 INFORMATION [cluster-ClusterId{value='5b4dc889b65c2c235477a760', description='null'}-localhost:27017] com.mongodb.diagnostics.logging.JULLogger.log Opened connection [connectionId{localValue:1, serverValue:25}] to localhost:27017
17-Jul-2018 12:44:25.828 INFORMATION [cluster-ClusterId{value='5b4dc889b65c2c235477a760', description='null'}-localhost:27017] com.mongodb.diagnostics.logging.JULLogger.log Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 2, 21]}, minWireVersion=0, maxWireVersion=4, maxDocumentSize=16777216, roundTripTimeNanos=550534}
17-Jul-2018 12:44:25.903 INFORMATION [http-nio-8089-exec-3] com.mongodb.diagnostics.logging.JULLogger.log Opened connection [connectionId{localValue:2, serverValue:26}] to localhost:27017
17-Jul-2018 12:44:25.930 SCHWERWIEGEND [http-nio-8089-exec-3] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
17-Jul-2018 12:44:25.930 SCHWERWIEGEND [http-nio-8089-exec-3] org.apache.catalina.core.StandardContext.startInternal Context [/epcis] startup failed due to previous errors
17-Jul-2018 12:44:25.959 WARNUNG [http-nio-8089-exec-3] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [epcis] appears to have started a thread named [cluster-ClusterId{value='5b4dc889b65c2c235477a760', description='null'}-localhost:27017] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@10.0.1/jdk.internal.misc.Unsafe.park(Native Method)
 java.base@10.0.1/java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
 java.base@10.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source)
 com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.waitForSignalOrTimeout(DefaultServerMonitor.java:224)
 com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.waitForNext(DefaultServerMonitor.java:205)
 com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:153)
 java.base@10.0.1/java.lang.Thread.run(Unknown Source)
17-Jul-2018 12:44:25.960 WARNUNG [http-nio-8089-exec-3] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [epcis] appears to have started a thread named [pool-2-thread-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@10.0.1/jdk.internal.misc.Unsafe.park(Native Method)
 java.base@10.0.1/java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
 java.base@10.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source)
 java.base@10.0.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
 java.base@10.0.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
 java.base@10.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
 java.base@10.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
 java.base@10.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
 java.base@10.0.1/java.lang.Thread.run(Unknown Source)
17-Jul-2018 12:44:25.960 WARNUNG [http-nio-8089-exec-3] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [epcis] appears to have started a thread named [DefaultQuartzScheduler_Worker-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@10.0.1/java.lang.Object.wait(Native Method)
 org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:568)
17-Jul-2018 12:44:25.960 WARNUNG [http-nio-8089-exec-3] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [epcis] appears to have started a thread named [DefaultQuartzScheduler_Worker-2] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@10.0.1/java.lang.Object.wait(Native Method)
 org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:568)
17-Jul-2018 12:44:25.961 WARNUNG [http-nio-8089-exec-3] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [epcis] appears to have started a thread named [DefaultQuartzScheduler_Worker-3] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@10.0.1/java.lang.Object.wait(Native Method)
 org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:568)
17-Jul-2018 12:44:25.961 WARNUNG [http-nio-8089-exec-3] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [epcis] appears to have started a thread named [DefaultQuartzScheduler_Worker-4] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@10.0.1/java.lang.Object.wait(Native Method)
 org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:568)
17-Jul-2018 12:44:25.961 WARNUNG [http-nio-8089-exec-3] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [epcis] appears to have started a thread named [DefaultQuartzScheduler_Worker-5] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@10.0.1/java.lang.Object.wait(Native Method)
 org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:568)
17-Jul-2018 12:44:25.962 WARNUNG [http-nio-8089-exec-3] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [epcis] appears to have started a thread named [DefaultQuartzScheduler_Worker-6] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@10.0.1/java.lang.Object.wait(Native Method)
 org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:568)
17-Jul-2018 12:44:25.962 WARNUNG [http-nio-8089-exec-3] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [epcis] appears to have started a thread named [DefaultQuartzScheduler_Worker-7] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@10.0.1/java.lang.Object.wait(Native Method)
 org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:568)
17-Jul-2018 12:44:25.963 WARNUNG [http-nio-8089-exec-3] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [epcis] appears to have started a thread named [DefaultQuartzScheduler_Worker-8] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@10.0.1/java.lang.Object.wait(Native Method)
 org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:568)
17-Jul-2018 12:44:25.963 WARNUNG [http-nio-8089-exec-3] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [epcis] appears to have started a thread named [DefaultQuartzScheduler_Worker-9] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@10.0.1/java.lang.Object.wait(Native Method)
 org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:568)
17-Jul-2018 12:44:25.964 WARNUNG [http-nio-8089-exec-3] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [epcis] appears to have started a thread named [DefaultQuartzScheduler_Worker-10] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@10.0.1/java.lang.Object.wait(Native Method)
 org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:568)
17-Jul-2018 12:44:25.964 WARNUNG [http-nio-8089-exec-3] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [epcis] appears to have started a thread named [DefaultQuartzScheduler_QuartzSchedulerThread] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@10.0.1/java.lang.Object.wait(Native Method)
 org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:427)

**Comment by JaewookByun** [comment]
Thanks for being interested in our project. 

I have not checked all the working environment but
I strongly believe the version of your Tomcat is not compatible with Oliot EPCIS. 
Please use Tomcat 8.x not Tomcat 8.5.x.
I cannot be 100% sure about Java 10. But, it should be Oracle JDK.
Because, Oliot EPCIS leverages the parallelism of Oracle JDK.

**Comment by thomaskarlrichter** [comment]
Thank you very much for your fast answer. 

I installed Tomcat 8.x.
now it works even with mongod 4.0 running on macosx! (but in the logs there is the the output:
{ driver: { name: "mongo-java-driver", version: "3.4.2" }, os: { type: "Darwin", name: "Mac OS X", architecture: "x86_64", version: "10.12.6" }, platform: "Java/Oracle Corporation/1.8.0_171-b11" }
so may be I have to install a mongo-java-driver version 4.x?

but it works so fare. great!

**Comment by JaewookByun** [comment]
Thank you for proving another working environment. 

Regarding the version of MongoDB, the latest version of Java driver is 
3.8.0 for MongoDB v4.0.x so I updated it. 

I close this issue!
