### ISSUE TITLE
How to generate Java file from EPCIS xsd file

### ISSUE THREAD

**Issue by Avadhesh-Patel** [JaewookByun/epcis#38]
I am getting following exception while generating Java class
**org.xml.sax.SAXParseException EPCglobal-epcis-1_2.xsd**
**src-resolve: Cannot resolve the name 'sbdh:StandardBusinessDocumentHeader'**

**Comment by JaewookByun** [comment]
Dear Avadhesh-Patel, 

You might want to generate Java classes from the xml schema in your own purpose. 
In our case, the Java classes, locased in https://github.com/JaewookByun/epcis/tree/master/epcis/src/main/java/org/oliot/model/epcis
, are generated by the following command
xjc -nv -d src -p org.oliot.model.epcis EPCglobal-epcis-1_2.xsd

I hope it helps you

Best Regards,
Jaewook Byun
Ph.D. Assistant Professor, Halla University, Republic of Korea

**Comment by Avadhesh-Patel** [comment]
Thanks @JaewookByun

**Comment by JaewookByun** [comment]
I close this issue.
