### ISSUE TITLE
Communication problemes Oliot and simple Client based on epcis-1.2-spec

### ISSUE THREAD

**Issue by led-del** [JaewookByun/epcis#43]
A self developed minimalistic client isn't able to request query names from Oliot EPCIS v1.2.1.
Operation: GetQueryNames failed because server responded with Unexpected element.
`javax.xml.ws.soap.SOAPFaultException: Unexpected element {urn:epcglobal:epcis-query:xsd:1}GetQueryNamesResponse found.   Expected {urn:epcglobal:epcis-query:xsd:1}GetQueryNamesResult.`

Client: self developed based on https://www.gs1.org/standards/epcis/artifacts/1-2

As I'm reading the specifiation I'd expect the GetQueryNamesResult but it sends back a GetQueryNamesRepsonse. 
I'v already tried to use the wsdl file which is downloadable from the server  (http://localhost:8080/epcis/webservice/QueryService?wsdl) but it's not working with wsimport or cfx.

Do you have any further idea?

**Comment by JaewookByun** [comment]
Hi led-del, 

You can refer to web.xml, beans.xml, CoreQueryService.java, SoapQueryService.java, etc. 
Also, for the client side, you can refer to SoapTest.java on the test package. 

Also, you can test the following by using Postman, curl, etc., 

HTTP.POST -> http://localhost:8080/epcis/webservice/QueryService

Body:
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:query="urn:epcglobal:epcis-query:xsd:1"> 
    <soapenv:Header/> 
    <soapenv:Body> 
        <query:GetQueryNames/> 
    </soapenv:Body> 
</soapenv:Envelope>

We hope it helps you.
