### ISSUE TITLE
Need regex search in EQ_bizTransaction_ parameter

### ISSUE THREAD

**Issue by farazdeveloper** [JaewookByun/epcis#56]
I need regex to search data in  EQ_bizTransaction_ parameter. 

- Why you didn't provide regex search in this EQ_bizTransaction_ parameter? 
- At code level, Could i change search query for this parameter in EQ_bizTransaction_ according to regex or after changing will i face any issue?

**Comment by JaewookByun** [comment]
Dear farazdeveloper, 

EQ_* queries in EPCIS standard are originally for filtering events where queried values are not exactly matched with the given value.
But as an extension, we support regex search for some simple event queries. 
Your contribution is welcome. 
If you want to contribute to support regex for EQ_bizTransaction_*, 
please refer to other regex queries and minimally update the codes and test it and then do pull request. 

Thank you
