### ISSUE TITLE
Version 2.10 - Query by EQ_eventID is not working

### ISSUE THREAD

**Issue by dnguyennirainc** [JaewookByun/epcis#74]
Query by EQ_eventID does not find the desired event by EQ_eventID.

When queried for all events, EPCIS returns an eventID: 1234
![Screenshot 2023-05-17 3 06 16 PM](https://github.com/JaewookByun/epcis/assets/133913216/1a17fe1a-7a38-40ab-aa67-3d368a1605ae)

But when queried for event with eventID: 1234, EPCIS returns no results
![Screenshot 2023-05-17 3 06 35 PM](https://github.com/JaewookByun/epcis/assets/133913216/c9eb3238-5f9c-483b-abcc-99674f892735)

**Comment by JaewookByun** [comment]
Thanks for your error report. We would fix the error soon at that version.
Meanwhile, I recommend you to use the latest version 2.2.0

**Comment by JaewookByun** [comment]
We found the point that generates the errors. 
You can see it now works well in the open server.

**Comment by JaewookByun** [comment]
Now, epcis v2.1.0 is fixed against this issue.
Thanks for your report while we still recommend you to use oliot-epcis 2.2.0

The issue closes

**Comment by dnguyennirainc** [comment]
Thank you, Professor Jack.  Understood on v2.2.0.  We will be evaluating
upgrading to that version soon.
