### ISSUE TITLE
Case Sensitive Resource names

### ISSUE THREAD

**Issue by Siko91** [JaewookByun/epcis#76]
Hello.

Firstly, thank you for developing this software.

The issue I want to report is an inconsistency with the names of these files:

 > epcis-server/src/main/resources/schema/EPCglobal-epcis-2_0.xsd
 epcis-server/src/main/resources/schema/EPCglobal-epcis-masterdata-2_0.xsd
 epcis-server/src/main/resources/schema/EPCglobal-epcis-query-2_0.xsd
 epcis-server/src/main/resources/schema/EPCglobal.xsd
 
 It appears that you developed this software entirely on Microsoft Windows, where filenames are not case sensitive.
 While I was attempting to configure the server to run in Docker, I noticed that in some places in the code, these files are referenced as `EPCglobal-*`, while in others they are referenced as `epcglobal-*`
 (It took me an embarrassing amount of hours to figure out why some resources were found, while others weren't.)
 
 The way I fixed this in my own copy of the project was by renaming these four files to always be in lowercase, and then replacing any mention of `EPCglobal` with `epcglobal`.
 I am not opening a pull request with these changes, because I thought that you might prefer to do the exact opposite and replace all `epcglobal` mentions with `EPCglobal`.
 Regardless of which approach you prefer, please make sure that the filenames stay consistent.
 
 Best Regards from Bulgaria,
 Aleksandar Dinkov

**Comment by Siko91** [comment]
P.S. - If you wish, I can share the docker configuration files, once they are fully ready.
I did a bit of a sloppy job with them, since I am not actually a Java developer (I only know C# and NodeJS), but I ended up somehow making it work in the end.

> The biggest challenge was building an "uber-jar" inside of the container - I completely failed at that, since I have no experience with `Maven`.
However I somehow made it work anyway, by simply zipping the right things in the JAR file manually with `zip` and `unzip` commands.
It is a bit embarrassing as a solution, but whatever - at least I no longer have to deal with the `pom.xml` file. :D

**Comment by JaewookByun** [comment]
Dear Aleksandar Dinkov, 

Thanks for your report. I just made the names of the schema files lower cases. 

Best regards,
Jack

**Comment by JaewookByun** [comment]
> Hello.
> 
> Firstly, thank you for developing this software.
> 
> The issue I want to report is an inconsistency with the names of these files:
> 
> > epcis-server/src/main/resources/schema/EPCglobal-epcis-2_0.xsd
> > epcis-server/src/main/resources/schema/EPCglobal-epcis-masterdata-2_0.xsd
> > epcis-server/src/main/resources/schema/EPCglobal-epcis-query-2_0.xsd
> > epcis-server/src/main/resources/schema/EPCglobal.xsd
> 
> It appears that you developed this software entirely on Microsoft Windows, where filenames are not case sensitive. While I was attempting to configure the server to run in Docker, I noticed that in some places in the code, these files are referenced as `EPCglobal-*`, while in others they are referenced as `epcglobal-*` (It took me an embarrassing amount of hours to figure out why some resources were found, while others weren't.)
> 
> The way I fixed this in my own copy of the project was by renaming these four files to always be in lowercase, and then replacing any mention of `EPCglobal` with `epcglobal`. I am not opening a pull request with these changes, because I thought that you might prefer to do the exact opposite and replace all `epcglobal` mentions with `EPCglobal`. Regardless of which approach you prefer, please make sure that the filenames stay consistent.
> 
> Best Regards from Bulgaria, Aleksandar Dinkov

Dear Aleksandar Dinkov,

Thanks for your report. I just made the names of the schema files lower cases.

Best regards,
Jack

**Comment by JaewookByun** [comment]
> P.S. - If you wish, I can share the docker configuration files, once they are fully ready. I did a bit of a sloppy job with them, since I am not actually a Java developer (I only know C# and NodeJS), but I ended up somehow making it work in the end.
> 
> > The biggest challenge was building an "uber-jar" inside of the container - I completely failed at that, since I have no experience with `Maven`.
> > However I somehow made it work anyway, by simply zipping the right things in the JAR file manually with `zip` and `unzip` commands.
> > It is a bit embarrassing as a solution, but whatever - at least I no longer have to deal with the `pom.xml` file. :D

Really appreciate that you contribute to this project. 
If ready, make pull request by packaging all the updates into /epcis-docker
I hope there is no change in the other directories. (e.g., / , /epcis-server , /.git)

Thank you so much for being interested in this project. 

Best regards,
Jack

**Comment by Siko91** [comment]
Dockerfiles have a security limit - they cannot access folders above their own - only bellow.
(they can't go to "./../epcis-server")
For that reason, most people put the Dockerfile file in the root directory.

There is 1 workaround if you really wish to keep it all in a sub-folder.
The workaround is to tell the "docker-compose" configuration to run the Dockerfile as if it is in the root folder, even tho it's not.
However that comes with some limitations.
You'll only be able to run the project with the "docker-compose" command. You won't be easily able to build the container independently with "docker build".

I recommend keeping the Dockerfile at the root directory and keeping any other docker related files in the /epcis-docker directory.

**Comment by JaewookByun** [comment]
> Dockerfiles have a security limit - they cannot access folders above their own - only bellow. (they can't go to "./../epcis-server") For that reason, most people put the Dockerfile file in the root directory.
> 
> There is 1 workaround if you really wish to keep it all in a sub-folder. The workaround is to tell the "docker-compose" configuration to run the Dockerfile as if it is in the root folder, even tho it's not. However that comes with some limitations. You'll only be able to run the project with the "docker-compose" command. You won't be easily able to build the container independently with "docker build".
> 
> I recommend keeping the Dockerfile at the root directory and keeping any other docker related files in the /epcis-docker directory.

I got the points. 
Then, please carefully do not modify the other codes when you insert some files on the root directory
Thanks for your contribution

**Comment by Siko91** [comment]
Closing the issue, as I don't think there is anything left to discuss on this topic.
